# action.yml
name: 'IoT Edge Dev'
description: 'Iot Edge cli'
inputs:
  iothub_connection_string:
    description: 'the iot hub connection string'
    required: true
  file_path:
    description: 'file path of the manifest file'
    required: false
    default: 'deployment.template.json'
  command:
    description: 'the command to run'
    required: true
runs:
  using: 'docker'
  image: 'dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.file_path }} 