# action.yml
name: 'IoT Edge Dev'
description: 'Iot Edge cli'
inputs:
  iothub_connection_string:  # id of input
    description: 'the iot hub connection string'
    required: true
  file_path:  # id of input
    description: 'file path of the manifest file'
    required: false
    default: 'deployment.template.json'
  command:  # id of input
    description: 'the command to run'
    required: true
runs:
  using: 'docker'
  image: 'mcr.microsoft.com/iotedge/iotedgedev:latest' 
  args: ['pwd', 'iotedgedev', '${{ inputs.command }}', '-f', '${{ inputs.file_path }}'] 