# action.yml
name: 'IoT Edge Dev'
description: 'Iot Edge cli'
inputs:
  iothub_connection_string:  # id of input
    description: 'the iot hub connection string'
    required: true
  command:  # id of input
    description: 'the command to run'
    required: true
runs:
  using: 'docker'
  image: 'mcr.microsoft.com/iotedge/iotedgedev:latest'
  args: ['ls', '/github/workspace/lora']