# action.yml
name: 'IoT Edge Dev'
description: 'Iot Edge cli'
inputs:
  iothub_connection_string:  # id of input
    description: 'the iot hub connection string'
    required: true
runs:
  using: 'docker'
  image: 'dockerfile'
  entrypoint: 'entrypoint.sh'